### PR TITLE
Some minor filesystem related cleanups

### PR DESCRIPTION
**Pull request by btw616**

### CODE REVIEW

**Review by ayushr2 — APPROVED** [review]
Thanks for the fix!

Could you just squash the commits and mention the 3 minor fixes in the commit message as bullet points?

**Comment by btw616** [comment]
> Thanks for the fix!
> 
> Could you just squash the commits and mention the 3 minor fixes in the commit message as bullet points?

Sure. Will do. :)

**Comment by ayushr2** [comment]
Thanks, I say because the commits from the PR are directly copied to the master branch when Copybara merges this. So that's why we ask contributors to squash commits (unless they are meant to be separate logical commits).

**Comment by btw616** [comment]
> Thanks, I say because the commits from the PR are directly copied to the master branch when Copybara merges this. So that's why we ask contributors to squash commits (unless they are meant to be separate logical commits).

I see. Thanks for the details!

**Pull request merged**
