### PR TITLE
kvm/arm64: set accessType when signal is SIGSEGV

### PR DESCRIPTION
**Pull request by zhlhahaha**
Only when PageFault happened, we need set accessType in order to
mapping the fault address.
Otherwise, it would trap in endless loop when exit vector is
El0ErrNMI or El0SyncUndef.

Signed-off-by: Howard Zhang <howard.zhang@arm.com>

### CODE REVIEW

**Comment by zhlhahaha** [comment]
cc: @avagin @lubinszARM

**Comment by lubinszARM** [comment]
LGTM

**Comment by avagin** [comment]
I did a similar change for x86 recently. Can we write a test that will catch this problem?

**Comment by zhlhahaha** [comment]
> I did a similar change for x86 recently. Can we write a test that will catch this problem?

Ok, I will write a test for it.

**Pull request merged**
