### PR TITLE
Enable pkg/atomicbitops support on arm64.

### PR DESCRIPTION
**Pull request by xiaobo55x**
Signed-off-by: Haibo Xu <haibo.xu@arm.com>
Change-Id: I1646aaa6f07b5ec31c39c318b70f48693fe59a7c

### CODE REVIEW

**Comment by xiaobo55x** [comment]
Ref #63

**Comment by xiaobo55x** [comment]
Hi @prattmic ,

Please help review this patch!

Thanks,
Haibo

**Comment by xiaobo55x** [comment]
Hi @avagin,

Please help trigger the kokoro run check for this PR.

Thanks,
Haibo

**Comment by avagin** [comment]
@xiaobo55x Done. We are sorry for long delays with reviewing your changes.

**Comment by xiaobo55x** [comment]
@avagin, Thanks so much for the review!

**Pull request merged**
