### PR TITLE
arm64 kvm: revert kpti related codes, and set upper pagetable as global

### PR DESCRIPTION
**Pull request by lubinszARM**
In order to improve the performance, some kpti related codes(TCR.A1) have
been reverted, and set kernel pagetable as global.

Also, this pr can solve the instability problem on Ampere altra host.

After the platform becomes stable, a series of KPTI patches will be uploaded.
Related issue: https://github.com/google/gvisor/issues/5176

* [x] request ACK from Ampere people

Signed-off-by: Robin Luk <lubin.lu@antgroup.com>

### CODE REVIEW

**Comment by lubinszARM** [comment]
@adamliyi 
Can you confirm it?
Thanks.

**Comment by adamliyi** [comment]
@lubinszARM ， Tested on server with Ampere Altra (2P, ubuntu2004+5.5.1 kernel),  this patch improves gVisor_KVM stability a lot:

- docker image adamliyi5440/ffmpeg_arm64:clang12: random hang and random crash disappeared
- adamliyi5440/ffmpeg_arm64:apt2004: Previously without ''--cpuset-cpus' option, runsc will randomly crash. With this patch, random crash disappeared

ffmpeg encoding speed does not change much.

Thanks for the patch!

> Hi @adamliyi
> Can you confirm it?
> Thanks.

**Review by adamliyi — APPROVED** [review]
Tested on Ampere Altra server with ffmpeg containers, gVisor_KVM stability improved by this patch.

**Comment by lubinszARM** [comment]
Thanks. @adamliyi

**Comment by lubinszARM** [comment]
Hi @avagin 
Any comments?
Thanks.

**Pull request merged**
