### PR TITLE
Add basic code for nfs filesystem.

### PR DESCRIPTION
**Pull request by caoruidong**
Initial implementation for nfs client, referenced the Linux kernel.

Signed-off-by: Ruidong Cao <crdfrank@gmail.com>

### CODE REVIEW

**Comment by avagin** [comment]
This code looks good for me. But I think we don't need merge it before basic operations are not implemented.

**Comment by caoruidong** [comment]
How many basic operations are there? 
By the way, I want to reuse code of https://github.com/vmware/go-nfs-client. But it depends on net package. Does the restriction on it (https://github.com/google/gvisor/blob/master/CONTRIBUTING.md) still exist?

**Comment by avagin** [comment]
> How many basic operations are there
... this should be something usable, so I think we should be able to read regular files.

> By the way, I want to reuse code of https://github.com/vmware/go-nfs-client. But it depends on net package.
You need to check that a license of this library is compatible with the gVisor license.

> Does the non-cgo restriction on it (https://github.com/google/gvisor/blob/master/CONTRIBUTING.md) still exist?
Cc: @nlacasse @amscanne

**Comment by nlacasse** [comment]
We already depend on the net library in a few places, but we avoid calling any methods that start the netpoller, due to performance implications.  (See https://github.com/golang/go/issues/32009).

The go-nfs-client library calls net.DialTCP, which will start the netpoller.

**Comment by amscanne** [comment]
Also importantly, net.DialTCP won't work unless passthrough mode is enabled. I think it would be possible to refactor the library slightly such that you could use a netstack gonet Connection [1]?

[1] https://github.com/google/netstack/blob/master/tcpip/adapters/gonet/gonet.go

**Comment by caoruidong** [comment]
Really thanks for your detailed explanation.

> You need to check that a license of this library is compatible with the gVisor license.

The license of https://github.com/vmware/go-nfs-client is BSD-2.

> Also importantly, net.DialTCP won't work unless passthrough mode is enabled. I think it would be possible to refactor the library slightly such that you could use a netstack gonet Connection [1]?

Thank you for this very useful advance. I plan to do like this too. But I find that gonet depends on net package and wonder how to use it. Now I'm clear.

**Comment by amscanne** [comment]
Just for clarity: we can review and merge once basic operations are in place, or we can add just the basic scaffolding. I would rather wait until there's something more substantial, but we did merge basic scaffolding for ext4 so we can do the same here (if you feel strongly).

**Comment by caoruidong** [comment]
Not so strong now. I think it will take some time. Close this PR first.

**Comment by tanjianfeng** [comment]
> Also importantly, net.DialTCP won't work unless passthrough mode is enabled. I think it would be possible to refactor the library slightly such that you could use a netstack gonet Connection [1]?
> 
> [1] https://github.com/google/netstack/blob/master/tcpip/adapters/gonet/gonet.go

Good to know we have such wrapper in sentry. But it seems to make more sense to have a wrapper ontop pkg/sentry/socket.

- Pros: transparent to the specific network type
- Cons: have to bear the heavy safemem copy inside pkg/sentry/socket

Just wonder how do we make the design choice?

**Pull request closed without merging**
