### PR TITLE
procfs: support /proc/[pid]/root file

### PR DESCRIPTION
**Pull request by cedriccchen**
support /proc/[pid]/root file

Signed-off-by: Chen Hui <cedriccchen@tencent.com>

### CODE REVIEW

**Comment by cedriccchen** [comment]
the procfs w/o this patch:
```
# ls -al /proc/self/
total 0
dr-xr-xr-x 7 root root 0 Sep 15 03:12 .
dr-xr-xr-x 5 root root 0 Sep 15 03:12 ..
-r--r--r-- 1 root root 0 Sep 15 03:12 auxv
-r--r--r-- 1 root root 0 Sep 15 03:12 cgroup
-r--r--r-- 1 root root 0 Sep 15 03:12 cmdline
-r--r--r-- 1 root root 0 Sep 15 03:12 comm
lrwxrwxrwx 1 root root 0 Sep 15 03:12 cwd -> /
-r--r--r-- 1 root root 0 Sep 15 03:12 environ
lrwxrwxrwx 1 root root 0 Sep 15 03:12 exe -> /usr/bin/ls
dr-xr-xr-x 2 root root 0 Sep 15 03:12 fd
dr-xr-xr-x 2 root root 0 Sep 15 03:12 fdinfo
-rw-r--r-- 1 root root 0 Sep 15 03:12 gid_map
-r-------- 1 root root 0 Sep 15 03:12 io
-r--r--r-- 1 root root 0 Sep 15 03:12 maps
-r-------- 1 root root 0 Sep 15 03:12 mem
-r--r--r-- 1 root root 0 Sep 15 03:12 mountinfo
-r--r--r-- 1 root root 0 Sep 15 03:12 mounts
dr-xr-xr-x 2 root root 0 Sep 15 03:12 net
dr-x--x--x 2 root root 0 Sep 15 03:12 ns
-r--r--r-- 1 root root 0 Sep 15 03:12 oom_score
-rw-r--r-- 1 root root 0 Sep 15 03:12 oom_score_adj
-r--r--r-- 1 root root 0 Sep 15 03:12 smaps
-r--r--r-- 1 root root 0 Sep 15 03:12 stat
-r--r--r-- 1 root root 0 Sep 15 03:12 statm
-r--r--r-- 1 root root 0 Sep 15 03:12 status
dr-xr-xr-x 3 root root 0 Sep 15 03:12 task
-rw-r--r-- 1 root root 0 Sep 15 03:12 uid_map
```

the procfs w/ this patch:
```
# ls -al /proc/self/   
total 0
dr-xr-xr-x 7 root root 0 Sep 15 03:15 .
dr-xr-xr-x 5 root root 0 Sep 15 03:14 ..
-r--r--r-- 1 root root 0 Sep 15 03:15 auxv
-r--r--r-- 1 root root 0 Sep 15 03:15 cgroup
-r--r--r-- 1 root root 0 Sep 15 03:15 cmdline
-r--r--r-- 1 root root 0 Sep 15 03:15 comm
lrwxrwxrwx 1 root root 0 Sep 15 03:15 cwd -> /
-r--r--r-- 1 root root 0 Sep 15 03:15 environ
lrwxrwxrwx 1 root root 0 Sep 15 03:15 exe -> /usr/bin/ls
dr-xr-xr-x 2 root root 0 Sep 15 03:15 fd
dr-xr-xr-x 2 root root 0 Sep 15 03:15 fdinfo
-rw-r--r-- 1 root root 0 Sep 15 03:15 gid_map
-r-------- 1 root root 0 Sep 15 03:15 io
-r--r--r-- 1 root root 0 Sep 15 03:15 maps
-r-------- 1 root root 0 Sep 15 03:15 mem
-r--r--r-- 1 root root 0 Sep 15 03:15 mountinfo
-r--r--r-- 1 root root 0 Sep 15 03:15 mounts
dr-xr-xr-x 2 root root 0 Sep 15 03:15 net
dr-x--x--x 2 root root 0 Sep 15 03:15 ns
-r--r--r-- 1 root root 0 Sep 15 03:15 oom_score
-rw-r--r-- 1 root root 0 Sep 15 03:15 oom_score_adj
lrwxrwxrwx 1 root root 0 Sep 15 03:15 root -> /
-r--r--r-- 1 root root 0 Sep 15 03:15 smaps
-r--r--r-- 1 root root 0 Sep 15 03:15 stat
-r--r--r-- 1 root root 0 Sep 15 03:15 statm
-r--r--r-- 1 root root 0 Sep 15 03:15 status
dr-xr-xr-x 3 root root 0 Sep 15 03:15 task
-rw-r--r-- 1 root root 0 Sep 15 03:15 uid_map
```

**Comment by nlacasse** [comment]
Thanks for the change.

Please add `root` to the `testStaticFiles` map here: https://github.com/google/gvisor/blob/master/pkg/sentry/fsimpl/proc/tasks_test.go#L88

That test is failing because the new `root` symlink is not expected.

**Comment by cedriccchen** [comment]
> Thanks for the change.
> 
> Please add `root` to the `testStaticFiles` map here: https://github.com/google/gvisor/blob/master/pkg/sentry/fsimpl/proc/tasks_test.go#L88
> 
> That test is failing because the new `root` symlink is not expected.

ok, done

**Comment by nlacasse** [comment]
Thanks!

**Pull request merged**
