### PR TITLE
Enable syscall fork_test on arm64.

### PR DESCRIPTION
**Pull request by xiaobo55x**
Signed-off-by: Haibo Xu <haibo.xu@arm.com>
Change-Id: I033692bcf4f8139df29e369a12b150d10fccbe32

### CODE REVIEW

**Comment by xiaobo55x** [comment]
Ref #63

**Comment by xiaobo55x** [comment]
Hi @avagin, @prattmic,

Please help review this patch!

Thanks,
Haibo

**Comment by avagin** [comment]
Our internal presubmit check fails:
```
Clang-format would introduce the following changes:
--- //depot/google3/third_party/gvisor/test/syscalls/linux/fork.cc
+++ //depot/google3/third_party/gvisor/test/syscalls/linux/fork.cc (formatted)
@@ -450,10 +450,12 @@
   //            int *child_tid);
 #if defined(__x86_64__)
   EXPECT_THAT(syscall(__NR_clone, SIGCHLD | CLONE_SETTLS, &stack, nullptr,
-                      nullptr, kNonCanonical), SyscallFailsWithErrno(EPERM));
+                      nullptr, kNonCanonical),
+              SyscallFailsWithErrno(EPERM));
 #elif defined(__aarch64__)
   EXPECT_THAT(syscall(__NR_clone, SIGCHLD | CLONE_SETTLS, &stack, nullptr,
-                      kNonCanonical, nullptr), SyscallFailsWithErrno(EPERM));
+                      kNonCanonical, nullptr),
+              SyscallFailsWithErrno(EPERM));
 #endif
 }
```

I recommend to run clang-format for all changed c++ files:
clang-format --style='{BasedOnStyle: Google, SortIncludes: false}' -i test/syscalls/linux/fork.cc

**Comment by xiaobo55x** [comment]
Fixed. Thanks!

**Pull request merged**
