### PR TITLE
hostinet: allow getsockopt(SO_RCVTIMEO) and getsockopt(SO_SNDTIMEO)

### LINKED ISSUE #6603: Host networking support for GetSockOpt: SO_RCVTIMEO, SO_SNDTIMEO
### Description

Used by ookla's speedtest server 

https://support.ookla.com/hc/en-us/articles/234578528-OoklaServer-Installation-Linux-Unix
```
OoklaServer X getsockopt(0x5 socket:[9], SOL_SOCKET, SO_RCVTIMEO, 0x7f1f3761f880, 0x7f1f3761f87c {length=16}) = 0x0 errno=92 (protocol not available) (3.885µs)
OoklaServer E close(0x5 socket:[9])
OoklaServer X close(0x5 socket:[9]) = 0x0 (73.19µs)
```

These seem harmless to my naive brain, perhaps they are trivial to support?

### Is this feature related to a specific bug?

_No response_

https://github.com/google/gvisor/blob/master/pkg/sentry/socket/hostinet/socket.go#L392
Add them here :) 

_No response_

### PR DESCRIPTION
**Pull request by kevinGC**
Fixes #6603

### CODE REVIEW

**Comment by benbuzbee** [comment]
Thanks for doing this Kevin

**Review by benbuzbee — APPROVED** [review]

**Comment by benbuzbee** [comment]
We merged this into our branches and it unblocked us; can it be merged?

**Comment by hbhasker** [comment]
Could you rebase this on tip and we can pull this in.

**Comment by kevinGC** [comment]
Sorry about the delay @benbuzbee. I forgot about this, then I had children (which did not help with remembering).

**Pull request merged**
