### PR TITLE
Enable pkg/sleep support on arm64.

### PR DESCRIPTION
**Pull request by xiaobo55x**
Signed-off-by: Haibo Xu <haibo.xu@arm.com>
Change-Id: I9071e698c1f222e0fdf3b567ec4cbd97f0a8dde9

### CODE REVIEW

**Comment by xiaobo55x** [comment]
#63

**Comment by xiaobo55x** [comment]
Hi @hbhasker @prattmic,

Please help review this patch!

Thanks,
Haibo

**Comment by amscanne** [comment]
LGTM, unless others have comments we can import shortly.

**Comment by xiaobo55x** [comment]
@amscanne, thanks for the review!

**Comment by xiaobo55x** [comment]
Hi @amscanne,

Could you help enable the import for this patch?

Thanks,
Haibo

**Comment by xiaobo55x** [comment]
Hi @prattmic,

Could you help review and trigger the import for this patch?

Thanks,
Haibo

**Pull request merged**
