### PR TITLE
Enable syscall ptrace test on arm64.

### PR DESCRIPTION
**Pull request by xiaobo55x**
Signed-off-by: Haibo Xu <haibo.xu@arm.com>
Change-Id: I5bb8fa7d580d173b1438d6465e1adb442216c8fa

### CODE REVIEW

**Comment by xiaobo55x** [comment]
Ref #63

**Comment by xiaobo55x** [comment]
Hi @avagin,

Please help review this patch which have a dependence on PR #2061 

Thanks,
Haibo

**Comment by avagin** [comment]
```
avagin@avagin:~/git/gvisor$ clang-format --style='{BasedOnStyle: Google, SortIncludes: false}' -i test/syscalls/linux/ptrace.cc
avagin@avagin:~/git/gvisor$ git diff
diff --git a/test/syscalls/linux/ptrace.cc b/test/syscalls/linux/ptrace.cc
index 7c44d484..b4277058 100644
--- a/test/syscalls/linux/ptrace.cc
+++ b/test/syscalls/linux/ptrace.cc
@@ -767,8 +767,7 @@ TEST(PtraceTest,
         << "orig_rax = " << regs.orig_rax;
     EXPECT_EQ(grandchild_pid, regs.rax);
 #elif defined(__aarch64__)
-    EXPECT_TRUE(regs.regs[8] == SYS_clone)
-        << "regs[8] = " << regs.regs[8];
+    EXPECT_TRUE(regs.regs[8] == SYS_clone) << "regs[8] = " << regs.regs[8];
     EXPECT_EQ(grandchild_pid, regs.regs[0]);
 #endif  // defined(__x86_64__)
   }
@@ -822,7 +821,7 @@ TEST(PtraceTest,
     iov.iov_base = &regs;
     iov.iov_len = sizeof(regs);
     EXPECT_THAT(ptrace(PTRACE_GETREGSET, child_pid, NT_PRSTATUS, &iov),
-                  SyscallSucceeds());
+                SyscallSucceeds());
 #if defined(__x86_64__)
     EXPECT_EQ(SYS_wait4, regs.orig_rax);
     EXPECT_EQ(grandchild_pid, regs.rax);
```

**Comment by xiaobo55x** [comment]
Done. Thanks!

**Comment by avagin** [comment]
Our presubmit hook is still failing:
```
avagin@avagin-glaptop:~/git/gvisor$ clang-format --style='{BasedOnStyle: Google, SortIncludes: false}' -i test/syscalls/linux/ptrace.cc 
avagin@avagin-glaptop:~/git/gvisor$ git diff
diff --git a/test/syscalls/linux/ptrace.cc b/test/syscalls/linux/ptrace.cc
index 178c82c8..926690eb 100644
--- a/test/syscalls/linux/ptrace.cc
+++ b/test/syscalls/linux/ptrace.cc
@@ -179,7 +179,8 @@ TEST(PtraceTest, GetSigMask) {
 
     // Install a signal handler for kBlockSignal to avoid termination and block
     // it.
-    TEST_PCHECK(signal(kBlockSignal, +[](int signo) {}) != SIG_ERR);
+    TEST_PCHECK(signal(
+                    kBlockSignal, +[](int signo) {}) != SIG_ERR);
     MaybeSave();
     TEST_PCHECK(sigprocmask(SIG_SETMASK, &blocked, nullptr) == 0);
     MaybeSave();
```

**Comment by xiaobo55x** [comment]
It seems a little weird! My local clang-format would try to format the file differently from that of your internal check.
```
root@entos-d06:~/go/src/gvisor.dev/gvisor# clang-format --style='{BasedOnStyle: Google, SortIncludes: false}' -i test/syscalls/linux/ptrace.cc
root@entos-d06:~/go/src/gvisor.dev/gvisor# git status
On branch ptrace_test
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   test/syscalls/linux/ptrace.cc

no changes added to commit (use "git add" and/or "git commit -a")
root@entos-d06:~/go/src/gvisor.dev/gvisor# git diff
diff --git a/test/syscalls/linux/ptrace.cc b/test/syscalls/linux/ptrace.cc
index 926690eb..178c82c8 100644
--- a/test/syscalls/linux/ptrace.cc
+++ b/test/syscalls/linux/ptrace.cc
@@ -179,8 +179,7 @@ TEST(PtraceTest, GetSigMask) {
 
     // Install a signal handler for kBlockSignal to avoid termination and block
     // it.
-    TEST_PCHECK(signal(
-                    kBlockSignal, +[](int signo) {}) != SIG_ERR);
+    TEST_PCHECK(signal(kBlockSignal, +[](int signo) {}) != SIG_ERR);
     MaybeSave();
     TEST_PCHECK(sigprocmask(SIG_SETMASK, &blocked, nullptr) == 0);
     MaybeSave();
root@entos-d06:~/go/src/gvisor.dev/gvisor#
```
Any way, I have fixed it manually to make the internal check pass.

**Pull request merged**
